### ISSUE TITLE
Cryptic error when you forget setting grad

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7910] opened 2019-08-13 04:27 UTC
Code:
```python
import chainer, numpy

x = chainer.Variable(numpy.ones((2, 3), 'float32'))
y = x ** 2
#y.grad = numpy.ones_like(y.array)
y.backward()
```

Error:
```
Traceback (most recent call last):
  File "/home/niboshi/t/a.py", line 6, in <module>
    y.backward()
  File "/data2/work/w/repos/chainer/chainer/variable.py", line 1470, in backward
    [(node, grad_var)], retain_grad, loss_scale)
  File "/data2/work/w/repos/chainer/chainer/_backprop.py", line 226, in _backprop_to_all
    func, target_input_indexes, out_grad, in_grad, is_debug)
  File "/data2/work/w/repos/chainer/chainer/_backprop_utils.py", line 140, in backprop_step
    _reraise_with_stack(func, e)
  File "/data2/work/w/repos/chainer/chainer/_backprop_utils.py", line 138, in backprop_step
    target_input_indexes, grad_outputs)
  File "/data2/work/w/repos/chainer/chainer/functions/math/basic_math.py", line 700, in backward
    return PowVarConstGrad(self.value).apply((inputs[0], gy[0]))
  File "/data2/work/w/repos/chainer/chainer/function_node.py", line 301, in apply
    self._check_data_type_forward(in_data)
  File "/data2/work/w/repos/chainer/chainer/function_node.py", line 397, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/data2/work/w/repos/chainer/chainer/functions/math/basic_math.py", line 713, in check_type_forward
    in_types[0].dtype == in_types[1].dtype,
AttributeError: 'NoneType' object has no attribute 'dtype'
```

More easily understood error is expected.

**Comment by kmaehashi** [comment] 2019-08-13 08:11
Duplicate of https://github.com/chainer/chainer/issues/3435

**Closed by kmaehashi** 2019-08-13 08:11 UTC
