### ISSUE TITLE
extensions.ParameterStatistics cannot work with default parameter in GPU mode

### ISSUE THREAD

**Issue by Hiroshiba** [chainer/chainer#3027] opened 2017-07-15 23:05 UTC
`extensions.ParameterStatistics` raise error in GPU mode at `numpy.count_nonzero` or `numpy.percentile` at https://github.com/chainer/chainer/blob/master/chainer/training/extensions/parameter_statistics.py#L106

The type of `link.param` is cupy.ndarray but these functions cannot take this type.
Other functions (like numpy.mean) use the instance method (like hoge.mean).

**Comment by niboshi** [comment] 2017-07-18 03:35
Thank you for reporting!
Can you provide a reproduction code and error log?

**Comment by koreyou** [comment] 2017-07-20 06:07
I've ran into the same problem with chainer 1.24.0.

The error was the following:

```
Traceback (most recent call last):
  File "/home/koreyou/.pyenv/versions/2.7.12/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/home/koreyou/.pyenv/versions/2.7.12/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/home/koreyou/.pyenv/versions/2.7.12/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "bin/my_training_script.py", line 12, in <module>
    """
  File "/home/koreyou/.pyenv/versions/myprogram/lib/python2.7/site-packages/chainer/training/trainer.py", line 298, in run
    entry.extension(self)
  File "/home/koreyou/.pyenv/versions/myprogram/lib/python2.7/site-packages/chainer/training/extensions/parameter_statistics.py", line 106, in __call__
    value = function(params)
  File "/home/koreyou/.pyenv/versions/myprogram/lib/python2.7/site-packages/chainer/training/extensions/parameter_statistics.py", line 57, in <lambda>
    99.87))
  File "/home/koreyou/.pyenv/versions/myprogram/lib/python2.7/site-packages/numpy/lib/function_base.py", line 4116, in percentile
    else:
  File "/home/koreyou/.pyenv/versions/myprogram/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3828, in _ureduce
    >>> A = fft(window, 2048) / 25.5
  File "/home/koreyou/.pyenv/versions/myprogram/lib/python2.7/site-packages/numpy/core/numeric.py", line 583, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: object __array__ method not producing an array
```
The `a` there was `cupy.core.core.ndarray`

I can see the reason behind this problem with following code:

```python
import cupy
import numpy as np

a = cupy.ones(3)
print a.__array__()  # this is actually fine
np.asanyarray(a)  # this raises the error
```

**Comment by t-sakai-kure** [comment] 2017-10-09 10:51
I am not sure this is an efficient way, but in my environment, the issue might be solved by simply wrapping params (at line 106 in parameter_statistics.py) by chainer.cuda.to_cpu, i.e., rewriting the line into 
`value = function(chainer.cuda.to_cpu(params))`
with
`import chainer`

**Comment by hvy** [comment] 2017-12-18 14:47
Thanks for reporting this issue. 

The extension constructor accepts a `statistics` argument which is expected to be a `dict` where the keys are log entry keys and values are functions such as `numpy.max` or in the case of GPUs `cupy.max`. 

This issue occurs because the default values are all numpy functions. If you know beforehand that you'll be using the GPU, you may want to pass a different `dict` where the values are `cupy` functions.

**Comment by t-sakai-kure** [comment] 2017-12-21 10:56
I see. You mean that we pass a different `statistics` to `ParameterStatistics`?
Below is an example:
```
gpu_statistics = { 
        'mean': cupy.mean,
        'std': cupy.std,
        'min': cupy.min,
        'max': cupy.max }
trainer.extend(extensions.ParameterStatistics(model, statistics=gpu_statistics))
```

I did not try it, but it sounds good. It would be an alternative way to use `to_cpu`.
If there are any other way to handle `model` regardless of CPU or GPU, it would be great, but the current solutions are also fine for me at this point.

**Comment by hvy** [comment] 2017-12-21 15:16
Yes exactly. In most cases, I think `cupy` functions are faster. If you have multiple devices, you might want to wrap the functions above where you get the device from the input, e.g. `lambda x: xp = cuda.get_array_module(x); xp...` .

**Comment by hvy** [comment] 2018-02-14 07:05
@t-sakai-kure Is it fine to close this issue?

**Comment by t-sakai-kure** [comment] 2018-02-14 07:42
It's fine with me. If you can update the code so that the default behavior automatically chooses numpy or cupy, it would be useful for other users.

**Comment by hvy** [comment] 2018-02-18 04:15
@t-sakai-kure I created #4345 to automatically choose numpy/cupy. We should be able to close this issue after it's been merged.

**Comment by t-sakai-kure** [comment] 2018-02-18 06:10
@hvy That's great! Thanks a lot!

**Closed** 2018-02-28 06:30 UTC
