### ISSUE TITLE
Flaky test: `tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py::TestConvolution2DFunction`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#7946] opened 2019-08-15 05:14 UTC
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1835/TEST=chainer-py2,label=mn1-p100/console

>`FAIL tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py::TestConvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_25_{cover_all=False, groups=2, dilate=1, nobias=False, contiguous=None, W_dtype=float16, x_dtype=float16}::test_forward`

```
TestConvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_25_{cover_all=False, groups=2, dilate=1, nobias=False, contiguous=None, W_dtype=float16, x_dtype=float16}.test_forward _
13:01:48 
13:01:48 self = <chainer.testing._bundle.TestConvolution2DFunction_use_chainerx_false__chainer...se, contiguous=None, W_dtype=float16, x_dtype=float16} testMethod=test_forward>
13:01:48 args = (), kwargs = {}
13:01:48 e = FunctionTestError('Outputs do not match the expected values.\nIndices of outpu...]\n\n     [[ 0.83984375  1.10253906]\n      [ 0.80859375  1.1171875 ]]]]\n\n',)
13:01:48 s = <StringIO.StringIO instance at 0x7f5c66aa8c20>, k = 'x_dtype'
13:01:48 v = <type 'numpy.float16'>

:
:

13:01:48 E       FunctionTestError: Parameterized test failed.
13:01:48 E       
13:01:48 E       Base test method: TestConvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_forward
13:01:48 E       Test parameters:
13:01:48 E         cover_all: False
13:01:48 E         groups: 2
13:01:48 E         dilate: 1
13:01:48 E         nobias: False
13:01:48 E         contiguous: None
13:01:48 E         W_dtype: <type 'numpy.float16'>
13:01:48 E         x_dtype: <type 'numpy.float16'>
13:01:48 E       
13:01:48 E       
13:01:48 E       (caused by)
13:01:48 E       FunctionTestError: Outputs do not match the expected values.
13:01:48 E       Indices of outputs that do not match: 0
13:01:48 E       Expected shapes and dtypes: (2, 4, 2, 2):float16
13:01:48 E       Actual shapes and dtypes:   (2, 4, 2, 2):float16
13:01:48 E       
13:01:48 E       
13:01:48 E       Error details of output [0]:
13:01:48 E       
13:01:48 E       Not equal to tolerance rtol=0.01, atol=0.001
13:01:48 E       
13:01:48 E       (mismatch 100.0%)
13:01:48 E        x: array([[[[ 1.167969,  1.277344],
13:01:48 E                [ 1.152344,  0.912598]],
13:01:48 E       ...
13:01:48 E        y: array([[[[ 1.167969,  1.277344],
13:01:48 E                [ 1.152344,  0.912598]],
13:01:48 E       ...
13:01:48 E       
13:01:48 E       assert_allclose failed: 
13:01:48 E         shape: (2, 4, 2, 2) (2, 4, 2, 2)
13:01:48 E         dtype: float16 float16
13:01:48 E         i: (1, 2, 1, 1)
13:01:48 E         x[i]: -0.05615234375
13:01:48 E         y[i]: -0.0537109375
13:01:48 E         relative error[i]: 0.0454406738281
13:01:48 E         absolute error[i]: 0.00244140625
13:01:48 E       x: [[[[ 1.16796875  1.27734375]
13:01:48 E             [ 1.15234375  0.91259766]]
13:01:48 E       
13:01:48 E            [[-0.34790039 -0.76757812]
13:01:48 E             [-0.22021484 -1.08789062]]
13:01:48 E       
13:01:48 E            [[-0.61035156 -0.66308594]
13:01:48 E             [-1.84082031 -0.24072266]]
13:01:48 E       
13:01:48 E            [[ 1.27929688  0.86328125]
13:01:48 E             [ 0.44848633  0.68701172]]]
13:01:48 E       
13:01:48 E       
13:01:48 E           [[[ 0.93701172  0.859375  ]
13:01:48 E             [ 1.15820312  1.34472656]]
13:01:48 E       
13:01:48 E            [[-0.36254883 -0.12939453]
13:01:48 E             [-1.09179688 -0.32543945]]
13:01:48 E       
13:01:48 E            [[-0.56640625 -0.79101562]
13:01:48 E             [-1.55273438 -0.05615234]]
13:01:48 E       
13:01:48 E            [[ 0.83984375  1.10253906]
13:01:48 E             [ 0.80810547  1.11816406]]]]
13:01:48 E       y: [[[[ 1.16796875  1.27734375]
13:01:48 E             [ 1.15234375  0.91259766]]
13:01:48 E       
13:01:48 E            [[-0.34814453 -0.76757812]
13:01:48 E             [-0.22033691 -1.08789062]]
13:01:48 E       
13:01:48 E            [[-0.60986328 -0.66308594]
13:01:48 E             [-1.84082031 -0.24072266]]
13:01:48 E       
13:01:48 E            [[ 1.27929688  0.86328125]
13:01:48 E             [ 0.44824219  0.68701172]]]
13:01:48 E       
13:01:48 E       
13:01:48 E           [[[ 0.93701172  0.859375  ]
13:01:48 E             [ 1.15917969  1.34472656]]
13:01:48 E       
13:01:48 E            [[-0.36230469 -0.12939453]
13:01:48 E             [-1.09277344 -0.32543945]]
13:01:48 E       
13:01:48 E            [[-0.56591797 -0.79101562]
13:01:48 E             [-1.55273438 -0.05371094]]
13:01:48 E       
13:01:48 E            [[ 0.83984375  1.10253906]
13:01:48 E             [ 0.80859375  1.1171875 ]]]]
```

**Comment by niboshi** [comment] 2019-08-15 05:15
#7695 could be related, but I'm not sure.
This is `test_forward` test failure.

**Comment by emcastillo** [comment] 2019-08-19 02:26
Trying to reproduce this error on python2.7 with old cudnn

**Comment by emcastillo** [comment] 2019-08-19 04:30
1000 runs of each test
Forward : 1 failure

**Comment by emcastillo** [comment] 2019-08-20 07:32
Fix by relaxing tolerances

**Comment by emcastillo** [comment] 2019-08-26 01:44
Should be fixed by #7942

**Comment by kmaehashi** [comment] 2019-08-27 07:18
@emcastillo Reopened because of reoccurred failure?

**Comment by niboshi** [comment] 2019-11-13 08:47
Reoccurred in #8420

https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2490/TEST=chainer-py35,label=mn1-p100/console

`16:56:44 FAIL tests/chainer_tests/functions_tests/connection_tests/test_convolution_2d.py::TestConvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_true__cudnn_fast_batch_normalization_false__use_ideep_never_param_25_{W_dtype=float16, contiguous=None, cover_all=False, dilate=1, groups=2, nobias=False, x_dtype=float16}::test_forward`

```
16:56:43 E       chainer.testing.function_link.FunctionTestError: Parameterized test failed.
16:56:43 E       
16:56:43 E       Base test method: TestConvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_always__cudnn_deterministic_false__autotune_true__cudnn_fast_batch_normalization_false__use_ideep_never.test_forward
16:56:43 E       Test parameters:
16:56:43 E         W_dtype: <class 'numpy.float16'>
16:56:43 E         contiguous: None
16:56:43 E         cover_all: False
16:56:43 E         dilate: 1
16:56:43 E         groups: 2
16:56:43 E         nobias: False
16:56:43 E         x_dtype: <class 'numpy.float16'>
16:56:43 E       
16:56:43 E       
16:56:43 E       (caused by)
16:56:43 E       FunctionTestError: Outputs do not match the expected values.
16:56:43 E       Indices of outputs that do not match: 0
16:56:43 E       Expected shapes and dtypes: (2, 4, 2, 2):float16
16:56:43 E       Actual shapes and dtypes:   (2, 4, 2, 2):float16
16:56:43 E       
16:56:43 E       
16:56:43 E       Error details of output [0]:
16:56:43 E       
16:56:43 E       Not equal to tolerance rtol=0.01, atol=0.001
16:56:43 E       
16:56:43 E       (mismatch 3.125%)
16:56:43 E        x: array([[[[ 0.022949, -0.333984],
16:56:43 E                [-0.467529, -0.403809]],
16:56:43 E       ...
16:56:43 E        y: array([[[[ 0.022705, -0.333984],
16:56:43 E                [-0.467529, -0.403809]],
16:56:43 E       ...
16:56:43 E       
16:56:43 E       assert_allclose failed: 
16:56:43 E         shape: (2, 4, 2, 2) (2, 4, 2, 2)
16:56:43 E         dtype: float16 float16
16:56:43 E         i: (1, 3, 1, 0)
16:56:43 E         x[i]: -0.013671875
16:56:43 E         y[i]: -0.01611328125
16:56:43 E         relative error[i]: 0.1514892578125
16:56:43 E         absolute error[i]: 0.00244140625
16:56:43 E         relative tolerance * |y[i]|: 0.0001611328125
16:56:43 E         absolute tolerance: 0.001
16:56:43 E         total tolerance: 0.0011611328125
16:56:43 E       x: [[[[ 0.02294922 -0.33398438]
16:56:43 E             [-0.4675293  -0.40380859]]
16:56:43 E       
16:56:43 E            [[-1.01660156 -0.67578125]
16:56:43 E             [-0.80322266 -0.74316406]]
16:56:43 E       
16:56:43 E            [[-0.00292969  0.26806641]
16:56:43 E             [ 0.07617188  0.6328125 ]]
16:56:43 E       
16:56:43 E            [[-0.00244141  1.00097656]
16:56:43 E             [ 1.03222656  0.19287109]]]
16:56:43 E       
16:56:43 E       
16:56:43 E           [[[-1.3671875  -0.25170898]
16:56:43 E             [-0.57714844 -0.92675781]]
16:56:43 E       
16:56:43 E            [[-1.10839844 -1.15625   ]
16:56:43 E             [-0.71679688 -0.70703125]]
16:56:43 E       
16:56:43 E            [[ 0.70507812  0.87646484]
16:56:43 E             [ 0.25634766  0.8203125 ]]
16:56:43 E       
16:56:43 E            [[ 1.27050781  0.47680664]
16:56:43 E             [-0.01367188  0.88867188]]]]
16:56:43 E       y: [[[[ 0.02270508 -0.33398438]
16:56:43 E             [-0.4675293  -0.40380859]]
16:56:43 E       
16:56:43 E            [[-1.01660156 -0.67578125]
16:56:43 E             [-0.80322266 -0.74267578]]
16:56:43 E       
16:56:43 E            [[-0.00292969  0.26782227]
16:56:43 E             [ 0.07666016  0.63232422]]
16:56:43 E       
16:56:43 E            [[-0.00244141  1.00097656]
16:56:43 E             [ 1.03222656  0.19287109]]]
16:56:43 E       
16:56:43 E       
16:56:43 E           [[[-1.3671875  -0.25195312]
16:56:43 E             [-0.57666016 -0.92675781]]
16:56:43 E       
16:56:43 E            [[-1.10839844 -1.15625   ]
16:56:43 E             [-0.71679688 -0.70654297]]
16:56:43 E       
16:56:43 E            [[ 0.70507812  0.87646484]
16:56:43 E             [ 0.2565918   0.8203125 ]]
16:56:43 E       
16:56:43 E            [[ 1.27050781  0.47680664]
16:56:43 E             [-0.01611328  0.88867188]]]]
```

**Comment by toslunar** [comment] 2019-11-14 02:51
Also failed in https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2494/TEST=chainer-py35,label=mn1-p100/
`tests.chainer_tests.functions_tests.connection_tests.test_convolution_2d.TestConvolution2DFunction_use_chainerx_false__chainerx_device_None__use_cuda_true__cuda_device_0__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_25_{W_dtype=float16, contiguous=None, cover_all=False, dilate=1, groups=2, nobias=False, x_dtype=float16}.test_forward`

**Comment by emcastillo** [comment] 2019-11-18 07:53
It is interesting that the same failure is happening in both cases with/without cudnn.

**Comment by emcastillo** [comment] 2019-11-19 01:25
The reason behind the flakiness is the use of a numpy version < 1.17
1.17 fixed a bug in the float16 implementation.

What happens is that forward_expected is comparing all the backends against the cpu implementation using numpy. And when using CUDA the results in float16 might sightly differ in some corner cases dut to the cpu-gpu difference (numpy bug) in fp16 implementation. Other tests that rely on numpy for forward_expected are most likely to be affected by this.

Reproduced with numpy 1.15.3 -> 80 failures on 10000 test runs of 100 tests each
With numpy 1.17 0 failures.

Alternatives to fix this are:
1 ) Bump Numpy version in CI (not good)
2 ) Adjust tolerance or skip fp16 test for numpy versions < 1.17 (I have seen the relative error going up to 0.84619140625)
3 ) Compare cudnn against non-cudnn and viceversa. This ensures that fp16 values remain consistent in the gpu backend.

**Comment by niboshi** [comment] 2019-11-19 01:44
I vote for 2.
Perhaps you don't have to compare numbers at all (for example, by multiplying outputs by 0).
3 is a bit too tricky.

**Closed** 2019-11-23 07:56 UTC
Labels: cat:test, pr-ongoing, prio:high
