### ISSUE TITLE
Multi-GPU bug in LSTM

### ISSUE THREAD

**Issue by kaniblu** [chainer/chainer#1869] opened 2016-11-12 14:05 UTC
## The Problem ##

Currently, when `chainer.links.connection.LSTM` is bound to a gpu device (say `self._device_id`), it fails to allocate cell state `c` in the same GPU device as itself (`self._device_id`), causing an error stating that the gpu devices are different when performing forwarding or backwarding on the link. This problem is apparent when we want to use a gpu device with id > 0.

## Reproduction ##

Assuming that there are two gpu devices on the host machine, binding both of lstm link and input variable to the second gpu device will throw an error when performing `__call__`.

    from chainer import Variable, cuda, links as L
    import numpy as np

    lstm = L.LSTM(8, 8)
    lstm.to_gpu(1)

    var_x = Variable(cuda.to_gpu(np.random.random((8, 8)).astype(np.float32), 1))

    assert lstm._device_id == var_x.data.device_id == 1
    print("lstm device id: {}, var_x device id: {}".format(lstm._device_id, var_x.data.device.id))

    #The following line will throw ValueError
    lstm(var_x)

## Proposed Solution ##

In this previous example, the problem can be easily circumvented by adding a single line of following code:

    with cuda.Device(1):
        lstm(var_x)

I'm not sure if this is the intended behavior from the developers, but the behavior is unintuitive and the error message might be confusing to some users. Intuitively, the link should allocate `c` in the appropriate device (same as the bound device of itself). This can be achieved quite simply by modifying line 242 in `chainer/links/connection/lstm.py` into something like this:

    if xp == cupy:
        old_dev = cuda.Device()
        cuda.Device(self._device_id).use()

    self.c = variable.Variable(xp.zeros((batch, self.state_size), dtype=x.dtype), volatile='auto')

    if xp == cupy:
        old_dev.use()

But this does not seem optimal tbh. A better solution would have been having some kind of additional wrapping around allocation functions like `xp.zeros` that accepts device as a parameter.

As a side note, IMHO, there should be a common error checking function used in `__call__` that detects whether the input variable resides in a different device from the link. (The sanitizing function should also be togglable through `chainer.set_debug`).

**Comment by zori** [comment] 2016-11-15 07:49
Thank you for reporting this! As you noted, this was not the intended behaviour, but probably a bug (I did not reproduce it).

I believe @kamo-naoyuki is working on a solution (https://github.com/pfnet/chainer/pull/1876 was closed and a new PR will be created.)

**Comment by delta2323** [comment] 2017-11-27 04:46
Closed as I confirmed the reproduction code (with slight modification replacing `var_x.data.device_id` with `var_x.data.device.id`) no longer throw errors.

**Closed** 2017-11-27 04:46 UTC
Labels: bug
