### ISSUE TITLE
(chainer error) attributeerror: int object  has no attribute  eval

### ISSUE THREAD

**Issue by Yunpengjoin** [chainer/chainer#4594] opened 2018-04-09 19:06 UTC
when I try to implement the code on my ubuntu  16.04( code link is https://github.com/hillbig/binary_net);
I get the error when I run the : python train_mnist.py
it says 
attributeerror: int object  has no attribute  eval
(by the way, I installed the chainer just do : pip install chainer)
thank anyone can help!

**Comment by niboshi** [comment] 2018-04-09 23:38
Thank you for reporting! Could you paste the stack trace?

**Comment by Yunpengjoin** [comment] 2018-04-09 23:53
thank you for your reply, I have attached the  error report as a file 
![error report](https://user-images.githubusercontent.com/36309836/38528834-2fbacdfc-3c16-11e8-85ec-39f120719df6.PNG);
I did a few try; I noticed chainer had an update to v2.0 last year; I am wondering maybe it has removed some functions in your code, that it why it failed; but I am not sure;
looking forward to your reply :）

**Comment by niboshi** [comment] 2018-04-10 02:43
The code you mentioned (https://github.com/hillbig/binary_net) seems to be written for Chainer v1, and as you wrote, v1 to v2 was a big step and has many backward-incompatible changes (that's not the case in v3 and succeeding releases, though).

For this error, it seems [this line](https://github.com/hillbig/binary_net/blob/8597d1fd7d40876718c45a5133b8201e3c36348b/function_binary_linear.py#L34) is the cause.
You should rewrite this line
```
if n_in.eval() == 3:
```
as
```
if type_check.eval(n_in) == 3:
```
.

FYI, there's [a mention about this particular change](https://docs.chainer.org/en/stable/upgrade_v2.html#type-check-apis-are-updated-to-enable-lazy-building-of-the-error-messages) in the v1 to v2 upgrade guide.

**Comment by niboshi** [comment] 2018-04-16 02:03
Surely, as v1 to v2 is a big change, there must be several things to fix.

I'll close this issue for now, but please feel free to open an issue if you encounter a problem that is not covered in [the upgrade guides](https://docs.chainer.org/en/stable/upgrade.html).

**Closed by niboshi** 2018-04-16 02:03 UTC

**Comment by Yunpengjoin** [comment] 2018-04-16 03:42
Thank you so much, I have successfully fixed all errors

niboshi <notifications@github.com> 于 2018年4月15日周日 下午7:03写道：

**Comment by niboshi** [comment] 2018-04-16 04:00
Glad to hear that!
