### ISSUE TITLE
Flaky test: chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py::TestBatchNormalization::test_backward

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8145] opened 2019-09-19 07:42 UTC
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2079/TEST=chainer-py3,label=mn1-p100/console

Occurred in #8131

`FAIL tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py::TestBatchNormalization_use_chainerx_false__chainerx_device_None__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_9_{c_contiguous=True, dtype=float32, eps=2e-05, ndim=0, param_shape=(3, 4), running_statistics=False}::test_backward`

```
16:04:34 E           gradients (numeric):  -0.09132438895459064
16:04:34 E           gradients (backward): -0.09129361774414113
16:04:34 E           
16:04:34 E           x: numeric gradient, y: backward gradient
16:04:34 E           Not equal to tolerance rtol=0.0001, atol=1e-05
16:04:34 E           
16:04:34 E           Mismatch: 100%
16:04:34 E           Max absolute difference: 3.07712104e-05
16:04:34 E           Max relative difference: 0.00033706
16:04:34 E            x: array(-0.091324)
16:04:34 E            y: array(-0.091294)
16:04:34 E           
16:04:34 E           assert_allclose failed: 
16:04:34 E             shape: () ()
16:04:34 E             dtype: float64 float64
16:04:34 E             i: (0,)
16:04:34 E             x[i]: -0.09132438895459064
16:04:34 E             y[i]: -0.09129361774414113
16:04:34 E             relative error[i]: 0.0003370576302030566
16:04:34 E             absolute error[i]: 3.077121044950393e-05
16:04:34 E             relative tolerance * |y[i]|: 9.129361774414113e-06
16:04:34 E             absolute tolerance: 1e-05
16:04:34 E             total tolerance: 1.9129361774414116e-05
16:04:34 E           x: -0.09132439
16:04:34 E           y: -0.09129362
```

**Comment by hvy** [comment] 2019-09-19 10:00
Ran 10^6 repetitions locally without a single failure.

**Comment by hvy** [comment] 2019-09-20 00:34
I cannot reproduce this failure locally. Should we treat it as a rare case and close it until it reoccurs?

**Comment by niboshi** [comment] 2019-09-20 01:07
OK.

**Comment by hvy** [comment] 2019-09-27 07:24
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/2119/TEST=CHAINERX_chainer-py3,label=mn1-p100/console

```
16:10:50 FAIL ../../repo/tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py::TestBatchNormalization_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_85_{axis=0, c_contiguous=False, dtype=float32, eps=2e-05, input_shape=(5, 4), running_statistics=False}::test_backward

16:10:50 E           Mismatch: 100%
16:10:50 E           Max absolute difference: 0.00040794
16:10:50 E           Max relative difference: 0.0006204
16:10:50 E            x: array(0.657133)
16:10:50 E            y: array(0.657541)
16:10:50 E           
16:10:50 E           assert_allclose failed: 
16:10:50 E             shape: () ()
16:10:50 E             dtype: float64 float64
16:10:50 E             i: (0,)
16:10:50 E             x[i]: 0.6571334816915508
16:10:50 E             y[i]: 0.657541422748098
16:10:50 E             relative error[i]: 0.0006204035858946327
16:10:50 E             absolute error[i]: 0.0004079410565471786
16:10:50 E             relative tolerance * |y[i]|: 6.575414227480981e-05
16:10:50 E             absolute tolerance: 1e-05
16:10:50 E             total tolerance: 7.57541422748098e-05
16:10:50 E           x: 0.65713348
16:10:50 E           y: 0.65754142
```

Reoccurred, although this time with ChainerX. I'll reopen this issue and take a look at it.

**Comment by toslunar** [comment] 2019-09-27 08:34
```
Base test method: TestBatchNormalization_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_backward
Test parameters:
  axis: 0
  c_contiguous: False
  dtype: <class 'numpy.float32'>
  eps: 2e-05
  input_shape: (5, 4)
  running_statistics: False


(caused by)
AssertionError: check_backward failed (eps=0.001 atol=1e-05 rtol=0.0001)
inputs[0]:
array([[-0.49941039, 0.80378854, -0.01938385, -0.87215573],
       [-0.46540642, 0.79433566, 0.04526816, -0.37956932],
       [-0.80767149, 0.79968488, 0.20902939, 0.06915895],
       [-0.25238377, 0.83581710, 0.27215245, 0.95261574],
       [0.75989449, 0.77041215, -0.21527877, 0.07823878]], shape=(5, 4), dtype=float32, device='native:0')
inputs[1]:
array([0.93462908, 0.95781797, 0.99530250, 0.63202012], shape=(4,), dtype=float32, device='native:0')
inputs[2]:
array([-0.51229006, 0.79302269, -0.22160251, 0.03139535], shape=(4,), dtype=float32, device='native:0')
grad_outputs[0]:
array([[0.87104589, -0.12173251, 0.88580525, -0.18604197],
       [-0.62206638, 0.64985204, 0.77729779, 0.24739107],
       [0.09897874, -0.26451972, 0.8282575 , 0.40996665],
       [0.5825805 , 0.32507068, -0.90191352, 0.78573006],
       [-0.80562830, -0.43776247, -0.08406922, 0.15833165]], shape=(5, 4), dtype=float32, device='native:0')
directions[0]:
array([[0.11304589, -0.14597833, -0.12878275, 0.48632049],
       [-0.28568125, 0.16737632, -0.20202753, -0.29189471],
       [-0.17372658, 0.40889665, -0.06495940, 0.11445720],
       [0.05393436, -0.22958707, -0.09143412, -0.27756686],
       [0.03236360, 0.04851305, 0.02896282, 0.07794405]], shape=(5, 4), dtype=float64, device='native:0')
directions[1]:
array([0.18685710, -0.10954575, -0.11107793, 0.14072843], shape=(4,), dtype=float64, device='native:0')
directions[2]:
array([0.14924647, -0.00153983, 0.09467192, 0.02895652], shape=(4,), dtype=float64, device='native:0')
gradients (numeric):  array(0.65713348, shape=(), dtype=float64, device='native:0')
gradients (backward): array(0.65754142, shape=(), dtype=float64, device='native:0')
```

**Comment by niboshi** [comment] 2019-10-01 10:18
https://ci.preferred.jp/chainer.py27and35.cpu/31367/

Reoccurred in #8205

```

2019-10-01 19:10:56.118754 STDOUT 2244] | E           Base test method: TestBatchNormalization_use_chainerx_false__chainerx_device_None__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never.test_double_backward
-- | --
2019-10-01 19:10:56.118828 STDOUT 2244] | E           Test parameters:
2019-10-01 19:10:56.118830 STDOUT 2244] | E             c_contiguous: True
2019-10-01 19:10:56.118831 STDOUT 2244] | E             dtype: <class 'numpy.float16'>
2019-10-01 19:10:56.118832 STDOUT 2244] | E             eps: 2e-05
2019-10-01 19:10:56.118834 STDOUT 2244] | E             ndim: 0
2019-10-01 19:10:56.118851 STDOUT 2244] | E             param_shape: (3, 2, 3)
2019-10-01 19:10:56.118915 STDOUT 2244] | E             running_statistics: False
2019-10-01 19:10:56.118916 STDOUT 2244] | E             xdtype: <class 'numpy.float16'>
 

:


2019-10-01 19:10:59.125259 STDOUT 2244] | E           assert_allclose failed:
-- | --
2019-10-01 19:10:59.125260 STDOUT 2244] | E             shape: () ()
2019-10-01 19:10:59.125261 STDOUT 2244] | E             dtype: float64 float64
2019-10-01 19:10:59.125262 STDOUT 2244] | E             i: (0,)
2019-10-01 19:10:59.125264 STDOUT 2244] | E             x[i]: 0.542201194714592
2019-10-01 19:10:59.125287 STDOUT 2244] | E             y[i]: 0.5214743004260868
2019-10-01 19:10:59.125289 STDOUT 2244] | E             relative error[i]: 0.03974672245893943
2019-10-01 19:10:59.125356 STDOUT 2244] | E             absolute error[i]: 0.02072689428850527
2019-10-01 19:10:59.125358 STDOUT 2244] | E             relative tolerance * \|y[i]\|: 0.005214743004260868
2019-10-01 19:10:59.125359 STDOUT 2244] | E             absolute tolerance: 0.01
2019-10-01 19:10:59.125360 STDOUT 2244] | E             total tolerance: 0.015214743004260869
2019-10-01 19:10:59.125362 STDOUT 2244] | E           x: 0.54220119
2019-10-01 19:10:59.125364 STDOUT 2244] | E           y: 0.5214743
```

**Comment by niboshi** [comment] 2019-10-02 00:07
One more

https://travis-ci.org/chainer/chainer/jobs/592301315

`[2019-10-01 23:50:09] FAIL tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py::TestBatchNormalization_use_chainerx_false__chainerx_device_None__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_66_{c_contiguous=True, dtype=float16, eps=2e-05, ndim=0, param_shape=(3, 2, 3), running_statistics=False, xdtype=float16}::test_double_backward`

**Comment by hvy** [comment] 2019-10-02 11:32
Another one.

https://travis-ci.org/chainer/chainer/jobs/592487308

`
[2019-10-02 10:36:00] FAIL tests/chainer_tests/functions_tests/normalization_tests/test_batch_normalization.py::TestBatchNormalization_use_chainerx_true__chainerx_device_native:0__use_cuda_false__cuda_device_None__use_cudnn_never__cudnn_deterministic_false__autotune_false__cudnn_fast_batch_normalization_false__use_ideep_never_param_26_{c_contiguous=False, dtype=float16, eps=2e-05, ndim=0, param_shape=(3, 2, 3), running_statistics=True, xdtype=float16}::test_double_backward
`

**Closed** 2019-10-03 08:51 UTC
Labels: cat:test, prio:high
