### ISSUE TITLE
flaky test: `chainerx_tests/unit_tests/routines_tests/test_normalization.py::test_BatchNorm`

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#8199] opened 2019-09-30 08:25 UTC
https://travis-ci.org/chainer/chainer/jobs/591364861

`FAIL tests/chainerx_tests/unit_tests/routines_tests/test_normalization.py::test_BatchNorm_param_0_{contiguous=None}_param_0_{decay=None}_param_0_{eps=2e-05}_param_0_{param_dtype='float16'}_param_0_{x_dtype='float16'}_param_3_{axis=None, reduced_shape=(3, 4, 5, 2), x_shape=(2, 3, 4, 5, 2)}[native:0]`

```
[2019-09-30 08:05:44] E       chainer.testing.function_link.FunctionTestError: Outputs do not match the expected values.
[2019-09-30 08:05:44] E       Indices of outputs that do not match: 0
[2019-09-30 08:05:44] E       Expected shapes and dtypes: (2, 3, 4, 5, 2):float16
[2019-09-30 08:05:44] E       Actual shapes and dtypes:   (2, 3, 4, 5, 2):float16
[2019-09-30 08:05:44] E       
[2019-09-30 08:05:44] E       
[2019-09-30 08:05:44] E       Error details of output [0]:
[2019-09-30 08:05:44] E       
[2019-09-30 08:05:44] E       Not equal to tolerance rtol=0.1, atol=0.1
[2019-09-30 08:05:44] E       
[2019-09-30 08:05:44] E       (mismatch 0.4166666666666714%)
[2019-09-30 08:05:44] E        x: array([-0.1726  ,  0.3286  ,  0.4915  ,  1.105   ,  0.2152  ,  0.587   ,
[2019-09-30 08:05:44] E              -0.2905  , -0.012695,  0.554   , -1.178   , -0.3076  , -0.4988  ,
[2019-09-30 08:05:44] E              -0.3975  ,  0.4343  ,  0.813   ,  1.951   ,  0.2693  ,  0.758   ,...
[2019-09-30 08:05:44] E        y: array([-0.1726  ,  0.3286  ,  0.4915  ,  1.105   ,  0.2155  ,  0.587   ,
[2019-09-30 08:05:44] E              -0.2905  , -0.012695,  0.554   , -1.178   , -0.3071  , -0.4988  ,
[2019-09-30 08:05:44] E              -0.3975  ,  0.4343  ,  0.813   ,  1.951   ,  0.269   ,  0.758   ,...
[2019-09-30 08:05:44] E       
[2019-09-30 08:05:44] E       assert_allclose failed: 
[2019-09-30 08:05:44] E         shape: (2, 3, 4, 5, 2) (2, 3, 4, 5, 2)
[2019-09-30 08:05:44] E         dtype: float16 float16
[2019-09-30 08:05:44] E         i: (0, 2, 0, 4, 1)
[2019-09-30 08:05:44] E         x[i]: 0.070556640625
[2019-09-30 08:05:44] E         y[i]: -0.03399658203125
[2019-09-30 08:05:44] E         relative error[i]: 3.076171875
[2019-09-30 08:05:44] E         absolute error[i]: 0.10455322265625
:
```

**Comment by emcastillo** [comment] 2019-10-29 04:56
Close it since it cant be reproduced at the moment

**Closed** 2019-10-29 04:56 UTC
Labels: cat:test, prio:high
