### ISSUE TITLE
Test failure in test_batch_renormalization

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#3385] opened 2017-09-13 05:37 UTC
The discrepancy is beyond what can be soved by adjusting tolerances.

```
assert_allclose failed: 
  shape: () ()
  dtype: float64 float64
  i: (0,)
  x[i]: 0.89111328125
  y[i]: 0.2871745824813843
  err[i]: 0.6039386987686157
x: 0.89111328125
y: 0.2871745824813843
F
======================================================================
FAIL: test_backward_cpu (test_batch_renormalization.transplant_class.<locals>.C)  parameter: {'dtype': <class 'numpy.float16'>, 'ndim': 2, 'test': False}
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/work/w/repos/chainer/chainer/testing/condition.py", line 74, in wrapper
    fail()
  File "/data/work/w/repos/chainer/chainer/testing/condition.py", line 51, in fail
    instance.fail(msg)
AssertionError: 
Fail: 1, Success: 77

The first error message:
Traceback (most recent call last):
  File "/data/work/w/repos/chainer/chainer/testing/condition.py", line 60, in <lambda>
    lambda: f(ins, *args[1:], **kwargs),
  File "/data/work/w/repos/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py", line 135, in test_backward_cpu
    self.check_backward(self.x, self.gy)
  File "/data/work/w/repos/chainer/tests/chainer_tests/links_tests/normalization_tests/test_batch_renormalization.py", line 129, in check_backward
    eps=1e-2, **self.check_backward_options)
  File "/data/work/w/repos/chainer/chainer/gradient_check.py", line 341, in check_backward
    testing.assert_allclose(gx, gx_accum, atol=atol, rtol=rtol)
  File "/data/work/w/repos/chainer/chainer/testing/array.py", line 25, in assert_allclose
    x, y, atol=atol, rtol=rtol, verbose=verbose)
  File "/home/niboshi/anaconda/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 1395, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/niboshi/anaconda/anaconda3/lib/python3.6/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.1, atol=0.5

(mismatch 100.0%)
 x: array(0.89111328125)
 y: array(0.2871745824813843)
```

**Comment by hvy** [comment] 2017-10-30 02:43
This seems to be fixed, or at least, I cannot reproduce this failure. Can we close this ticket?

**Comment by kmaehashi** [comment] 2017-10-30 02:52
This is still occasionally happening in our CI server.

**Comment by niboshi** [comment] 2017-10-30 02:59
Yes, I just confirmed it still happens in the current master(e7dcc12a114cb6ed26523a53b1f5d866accb0f33) after 64044 iterations.

```
E   AssertionError: 
E   Fail: 1, Success: 64043
```

**Comment by kmaehashi** [comment] 2018-01-29 08:51
Moved to #3766.

**Closed by kmaehashi** 2018-01-29 08:51 UTC
Labels: bug, test
