### ISSUE TITLE
F.concat in v5.1.0 takes much more time than in v4.5.0 on GPU

### ISSUE THREAD

**Issue by kiyomaro927** [chainer/chainer#5958] opened 2019-01-07 13:56 UTC
I've recently upgraded chainer, and noticed the phenomenon.

On v5.1.0 and v4.5.0, I did an investigation using IPython as follows:
1. Create an 1D cupy.array (`zero`) and a list of 1,000 1D cupy.arrays (`ones`)
1. Concat `zero` and each array in `ones`
1. Measure the time taken by 1-2 several times.

[Chainer's official seq2seq example](https://github.com/chainer/chainer/blob/master/examples/seq2seq/seq2seq.py) has similar code around line 47-50. In the example, 1,000 (the length of `ones` in my experiment) corresponds to batchsize.

Here are the results. I printed out the developing environment at first.

**Result on Chainer 5.1.0 / Cupy 5.1.0**
```
In [1]: import chainer
    ...: import chainer.functions as F
    ...: import cupy

In [2]:  chainer.print_runtime_info()
Platform: Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid
Chainer: 5.1.0
NumPy: 1.15.4
CuPy:
  CuPy Version          : 5.1.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9010
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7101
  cuDNN Version         : 7101
  NCCL Build Version    : None
iDeep: Not Available

In [3]: with cupy.cuda.Device(3):
    ...:     zero = cupy.array([0], 'i')
    ...:     ones = [cupy.ones(3, 'i') for _ in range(1000)]
    ...:
    ...: def concat_test():
    ...:     with cupy.cuda.Device(3):
    ...:         _ = [F.concat([zero, one], axis=0) for one in ones]
    ...:

In [4]: %timeit concat_test()
3.11 s ± 53 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Result on Chainer 4.5.0 / Cupy 4.5.0**
```
In [1]: import chainer
    ...: import chainer.functions as F
    ...: import cupy

In [2]: chainer.print_runtime_info()
Platform: Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid
Chainer: 4.5.0
NumPy: 1.15.4
CuPy:
  CuPy Version          : 4.5.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9010
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7101
  cuDNN Version         : 7101
  NCCL Build Version    : None

In [3]: with cupy.cuda.Device(3):
    ...:     zero = cupy.array([0], 'i')
    ...:     ones = [cupy.ones(3, 'i') for _ in range(1000)]
    ...:
    ...: def concat_test():
    ...:     with cupy.cuda.Device(3):
    ...:         _ = [F.concat([zero, one], axis=0) for one in ones]
    ...:

In [4]: %timeit concat_test()
132 ms ± 6.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

5.1.0 took about 23 times more time (note that the units of time are different). This degrades the performance significantly.

**Comment by fiarabbit** [comment] 2019-01-08 03:20
This may originated from the difference in `cupy`, because in `chainer`, almost nothing is modified between v4.5.0 and v5.1.0.

```
$ git diff v4.5.0..v5.1.0 -- chainer/functions/array/concat.py
diff --git a/chainer/functions/array/concat.py b/chainer/functions/array/concat.py
index 448e425..c474863 100644
--- a/chainer/functions/array/concat.py
+++ b/chainer/functions/array/concat.py
@@ -2,7 +2,7 @@ import numpy
 import six

 import chainer
-from chainer.backends import cuda
+from chainer import backend
 from chainer.backends import intel64
 from chainer import function_node
 from chainer.utils import type_check
@@ -47,7 +47,7 @@ class Concat(function_node.FunctionNode):
             return self._forward_ideep(xs)

         # Generic implementation
-        xp = cuda.get_array_module(*xs)
+        xp = backend.get_array_module(*xs)
         return xp.concatenate(xs, self.axis),

     def _forward_ideep(self, xs):
```

**Comment by kiyomaro927** [comment] 2019-01-08 07:55
My python environment was the cause of the problem. My virtualenv was on a NFS and the access speed was the bottleneck.

**Comment by kiyomaro927** [comment] 2019-01-08 08:43
This is definitely a bug because stat syscall was called 2000 times in this snippet. 2 times per each `concat` call.

**Comment by niboshi** [comment] 2019-01-09 01:49
Perhaps it also helps to look at the call graph?

https://stackoverflow.com/questions/4544784/how-can-you-get-the-call-tree-with-python-profilers

**Comment by okuta** [comment] 2019-01-09 04:52
I tested following code. But. I could not reproduce it.
``` python
import chainer
import chainer.functions as F
import cupy
import cProfile

chainer.print_runtime_info()

with cupy.cuda.Device(3):
    zero = cupy.array([0], 'i')
    ones = [cupy.ones(3, 'i') for _ in range(1000)]

def concat_test():
    with cupy.cuda.Device(3):
        _ = [F.concat([zero, one], axis=0) for one in ones]

pr = cProfile.Profile()
pr.runcall(concat_test)
pr.print_stats()
```

**Comment by kiyomaro927** [comment] 2019-01-09 06:17
@beam2d 
I tested the following code that each element of `ones` is incremented. 5.1.0 also calls stat at each operation, so `F.concat` does not seem to be a problem. 

profile.py
```python
import chainer
import chainer.functions as F
import cupy
import cProfile

chainer.print_runtime_info()

with cupy.cuda.Device(3):
    zero = cupy.array([0], 'i')  # unused
    ones = [cupy.ones(3, 'i') for _ in range(1000)]

def add_test():
    with cupy.cuda.Device(3):
        _ = [one + 1 for one in ones]

pr = cProfile.Profile()
pr.runcall(add_test)
pr.print_stats()
```

```
(chainer-5.1.0) $ python profile.py | grep stat
     1000    0.001    0.000    0.012    0.000 <frozen importlib._bootstrap_external>:75(_path_stat)
        1    0.000    0.000    0.000    0.000 {built-in method _stat.S_ISDIR}
     1002    0.012    0.000    0.012    0.000 {built-in method posix.stat}
```

```
(chainer-4.5.0) $ python profile.py | grep stat
        1    0.000    0.000    0.000    0.000 {built-in method _stat.S_ISDIR}
        2    0.001    0.000    0.001    0.000 {built-in method posix.stat}
```

Just for your information, the `strace` results are here:
- [systrace for 5.1.0](https://gist.github.com/kiyomaro927/8f9ead642df93ba028b081ba7ba435a6)
- [systrace for 4.5.0](https://gist.github.com/90d8aac5c32619a020b728f00f1b1ca6)

**Comment by kiyomaro927** [comment] 2019-01-09 07:09
@niboshi 
Thanks for your suggestion. I have tried [pyinstrument](https://github.com/joerick/pyinstrument). Testing code is this.
```
import chainer
import chainer.functions as F
import cupy
import cProfile

chainer.print_runtime_info()

with cupy.cuda.Device(3):
    zero = cupy.array([0], 'i')
    ones = [cupy.ones(3, 'i') for _ in range(100000)]

def add_test():
    with cupy.cuda.Device(3):
        _ = [one + 1 for one in ones]

add_test()
```

Here are the results:
```
(chainer5.1.0) $ pyinstrument profile.py
Platform: Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid
Chainer: 5.1.0
NumPy: 1.15.4
CuPy:
  CuPy Version          : 5.1.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9010
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7101
  cuDNN Version         : 7101
  NCCL Build Version    : None
iDeep: Not Available
22.839 <module>  sample.py:1
├─ 17.152 add_test  sample.py:12
│  └─ 17.152 <listcomp>  sample.py:14
├─ 3.352 <listcomp>  sample.py:10
│  └─ 3.258 ones  cupy/creation/basic.py:88
│     └─ 0.234 compile_with_cache  cupy/cuda/compiler.py:120
├─ 1.676 <module>  chainer/__init__.py:1
│  ├─ 0.651 <module>  chainer/dataset/__init__.py:2
│  │  └─ 0.631 <module>  chainer/dataset/convert.py:1
│  │     └─ 0.625 <module>  chainer/backend.py:1
│  │        └─ 0.625 <module>  chainer/backends/cuda.py:29
│  │           └─ 0.600 <module>  cupy/__init__.py:1
│  │              └─ 0.401 <module>  cupy/testing/__init__.py:1
│  │                 └─ 0.395 <module>  cupy/testing/helper.py:1
│  │                    └─ 0.363 <module>  pkg_resources/__init__.py:16
│  ├─ 0.315 <module>  numpy/__init__.py:106
│  │  └─ 0.274 <module>  numpy/add_newdocs.py:10
│  │     └─ 0.269 <module>  numpy/lib/__init__.py:1
│  └─ 0.289 <module>  chainer/_environment_check.py:1
└─ 0.391 array  cupy/creation/from_data.py:5
```

```
(chainer4.5.0) $ pyinstrument profile.py
Platform: Linux-4.4.0-137-generic-x86_64-with-debian-stretch-sid
Chainer: 4.5.0
NumPy: 1.15.4
CuPy:
  CuPy Version          : 4.5.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 9000
  CUDA Driver Version   : 9010
  CUDA Runtime Version  : 9000
  cuDNN Build Version   : 7300
  cuDNN Version         : 7101
  NCCL Build Version    : 2213
11.999 <module>  sample.py:1
├─ 5.015 add_test  sample.py:12
│  └─ 5.015 <listcomp>  sample.py:14
├─ 4.823 <listcomp>  sample.py:10
│  └─ 4.703 ones  cupy/creation/basic.py:88
│     └─ 0.219 compile_with_cache  cupy/cuda/compiler.py:120
│        └─ 0.212 _preprocess  cupy/cuda/compiler.py:93
│           └─ 0.212 compile  cupy/cuda/compiler.py:239
├─ 1.603 <module>  chainer/__init__.py:1
│  ├─ 0.566 <module>  chainer/dataset/__init__.py:1
│  │  └─ 0.553 <module>  chainer/dataset/convert.py:1
│  │     └─ 0.548 <module>  chainer/backends/cuda.py:29
│  │        └─ 0.541 <module>  cupy/__init__.py:1
│  │           └─ 0.351 <module>  cupy/testing/__init__.py:1
│  │              └─ 0.347 <module>  cupy/testing/helper.py:1
│  │                 └─ 0.320 <module>  pkg_resources/__init__.py:16
│  ├─ 0.357 <module>  numpy/__init__.py:106
│  │  └─ 0.326 <module>  numpy/add_newdocs.py:10
│  │     └─ 0.322 <module>  numpy/lib/__init__.py:1
│  │        └─ 0.287 <module>  numpy/lib/type_check.py:3
│  │           └─ 0.280 <module>  numpy/core/__init__.py:1
│  ├─ 0.300 <module>  chainer/_environment_check.py:1
│  │  ├─ 0.173 <module>  numpy/distutils/system_info.py:121
│  │  └─ 0.123 <module>  numpy/distutils/__init__.py:1
│  └─ 0.146 <module>  chainer/functions/__init__.py:5
├─ 0.223 array  cupy/creation/from_data.py:4
└─ 0.142 print_runtime_info  chainer/_runtime_info.py:44
   └─ 0.142 get_runtime_info  chainer/_runtime_info.py:40
      └─ 0.142 __init__  chainer/_runtime_info.py:17
         └─ 0.128 get_runtime_info  cupyx/runtime.py:77
            └─ 0.128 __init__  cupyx/runtime.py:37
               └─ 0.122 _eval_or_error  cupyx/runtime.py:16
```

5.1.0 is faster to create arrays than 4.5.0, but takes much time to manipulate them. I couldn't find how stat syscall is called during the process. It may be called by the compiled Cython code.

**Comment by beam2d** [comment] 2019-01-09 07:43
Maybe I succeeded to reproduce the stat syscall in each kernel launch.

```
# foo.py
import cupy
ones = cupy.ones(1)
for _ in range(10):
    print('call')
    -ones
```

Running `strace -e trace=stat python foo.py`:

```
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/home/beam2d/.cupy/kernel_cache", {st_mode=S_IFDIR|0775, st_size=561152, ...}) = 0
stat("/home/beam2d/.cupy/kernel_cache/9106f92b9424466b864c5870a501feaa_2.cubin", {st_mode=S_IFREG|0600, st_size=3520, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
call
stat("/home/beam2d/miniconda3/lib/python3.6/site-packages/cupy/core", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
```

It looks kernel file cache is correctly working in my environment, but `stat("***/site-packages/cupy/core")` is called at every elementwise (or ufunc) kernel launch. I did not find where the call is made.

**Comment by kiyomaro927** [comment] 2019-01-09 08:06
@beam2d 
Thanks, I've confirmed that your code also produces the result on my environment.
And, 4.5.0 haven't made the call at each kernel launch.

**Comment by beam2d** [comment] 2019-01-09 08:37
(Based on a private suggestion by @niboshi,) I applied the patch cupy/cupy#1714 (which has already been merged to master but not backported to v5) to v5 branch and tried the script again, then the syscalls disappeared. It looks they were caused by an import statement in the kernel generation logic. I made [a backport PR](https://github.com/cupy/cupy/pull/1929) to CuPy v5.

**Comment by kiyomaro927** [comment] 2019-01-09 09:38
After installing cupy at v5 branch from source, the problem was solved.
I appreciate your support. I'll close this issue.

**Closed** 2019-01-09 09:38 UTC
