### ISSUE TITLE
Normal distribution test error

### ISSUE THREAD

**Issue by niboshi** [chainer/chainer#5183] opened 2018-08-06 05:58 UTC
Version: v5.0.0b3 master 313083e2f (with unrelated local changes)

I happen to encountered this error once. Several (~10) retries did not replicate the error.

```
self = <chainer.testing.parameterized.TestNormal_param_0 testMethod=test_log_survival_cpu>

    @skip_not_in_test_target('log_survival')
    def test_log_survival_cpu(self):
>       self.check_log_survival(False)

chainer/testing/distribution_test.py:217:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
chainer/testing/distribution_test.py:213: in check_log_survival
    array.assert_allclose(log_survival1, log_survival2)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = array([[[[ -2.6995385 ,  -4.594169  ,  -1.725811  ],
         [        -inf,  -1.1890926 ,  -0.3637382 ]],

        [[...    [[ -8.725308  ,  -0.10234644,  -1.169075  ],
         [ -7.818679  ,  -0.30798176,  -0.5043421 ]]]], dtype=float32)
y = array([[[[ -2.69953811,  -4.59416883,  -1.72581108],
         [-19.45005923,  -1.18909271,  -0.36373823]],

        [[...628318]],

        [[ -8.72533196,  -0.10234649,  -1.16907499],
         [ -7.81867423,  -0.30798173,  -0.50434207]]]])
atol = 1e-05, rtol = 0.0001, verbose = True

    def assert_allclose(x, y, atol=1e-5, rtol=1e-4, verbose=True):
        """Asserts if some corresponding element of x and y differs too much.
    
        This function can handle both CPU and GPU arrays simultaneously.
    
        Args:
            x: Left-hand-side array.
            y: Right-hand-side array.
            atol (float): Absolute tolerance.
            rtol (float): Relative tolerance.
            verbose (bool): If ``True``, it outputs verbose messages on error.
    
        """
        x = cuda.to_cpu(utils.force_array(x))
        y = cuda.to_cpu(utils.force_array(y))
        try:
            numpy.testing.assert_allclose(
                x, y, atol=atol, rtol=rtol, verbose=verbose)
        except AssertionError as e:
            f = six.StringIO()
            f.write(str(e) + '\n\n')
            f.write(
                'assert_allclose failed: \n' +
                '  shape: {} {}\n'.format(x.shape, y.shape) +
                '  dtype: {} {}\n'.format(x.dtype, y.dtype))
            if x.shape == y.shape:
                xx = x if x.ndim != 0 else x.reshape((1,))
                yy = y if y.ndim != 0 else y.reshape((1,))
                err = numpy.abs(xx - yy)
                i = numpy.unravel_index(numpy.argmax(err), err.shape)
                f.write(
                    '  i: {}\n'.format(i) +
                    '  x[i]: {}\n'.format(xx[i]) +
                    '  y[i]: {}\n'.format(yy[i]) +
                    '  err[i]: {}\n'.format(err[i]))
            opts = numpy.get_printoptions()
            try:
                numpy.set_printoptions(threshold=10000)
                f.write('x: ' + numpy.array2string(x, prefix='x: ') + '\n')
                f.write('y: ' + numpy.array2string(y, prefix='y: ') + '\n')
            finally:
                numpy.set_printoptions(**opts)
>           raise AssertionError(f.getvalue())
E           AssertionError: Parameterized test failed.
E           
E           Base test method: TestNormal.test_log_survival_cpu
E           Test parameters:
E             is_variable: True
E             log_scale_option: True
E             sample_shape: (3, 2)
E             shape: (2, 3)
E           
E           AssertionError: 
E           Not equal to tolerance rtol=0.0001, atol=1e-05
E           
E           x and y -inf location mismatch:
E            x: array([[[[ -2.699538,  -4.594169,  -1.725811],
E                    [      -inf,  -1.189093,  -0.363738]],
E           ...
E            y: array([[[[ -2.699538,  -4.594169,  -1.725811],
E                    [-19.450059,  -1.189093,  -0.363738]],
E           ...
E           
E           assert_allclose failed: 
E             shape: (3, 2, 2, 3) (3, 2, 2, 3)
E             dtype: float32 float64
E             i: (0, 0, 1, 0)
E             x[i]: -inf
E             y[i]: -19.450059229961028
E             err[i]: inf
E           x: [[[[ -2.6995385   -4.594169    -1.725811  ]
E                 [        -inf  -1.1890926   -0.3637382 ]]
E           
E                [[ -2.5937738   -2.7752094   -4.6005683 ]
E                 [ -8.515538    -0.6785957   -0.57707554]]]
E           
E           
E               [[[-14.930784    -3.6822066   -1.1309581 ]
E                 [ -0.09307714  -1.5061368   -0.32050824]]
E           
E                [[ -0.77060086  -0.19834344  -1.8238902 ]
E                 [ -0.17135604  -2.4612699   -1.4248217 ]]]
E           
E           
E               [[[ -1.0871338   -3.0167437   -0.56115   ]
E                 [ -0.8006804   -1.0286884   -1.6662831 ]]
E           
E                [[ -8.725308    -0.10234644  -1.169075  ]
E                 [ -7.818679    -0.30798176  -0.5043421 ]]]]
E           y: [[[[ -2.69953811  -4.59416883  -1.72581108]
E                 [-19.45005923  -1.18909271  -0.36373823]]
E           
E                [[ -2.59377402  -2.77520922  -4.60056894]
E                 [ -8.51556474  -0.67859571  -0.57707559]]]
E           
E           
E               [[[-14.92220056  -3.68220693  -1.13095808]
E                 [ -0.09307717  -1.50613677  -0.32050823]]
E           
E                [[ -0.77060089  -0.19834346  -1.82389028]
E                 [ -0.17135607  -2.46126976  -1.4248217 ]]]
E           
E           
E               [[[ -1.08713369  -3.01674318  -0.56115003]
E                 [ -0.80068042  -1.02868841  -1.66628318]]
E           
E                [[ -8.72533196  -0.10234649  -1.16907499]
E                 [ -7.81867423  -0.30798173  -0.50434207]]]]

chainer/testing/array.py:50: AssertionError
```

**Comment by toslunar** [comment] 2018-08-10 06:30
I believe the issue is fixed by #5185.  Please reopen the issue if it's observed again.

**Closed by toslunar** 2018-08-10 06:30 UTC
