### ISSUE TITLE
Why chainer.links.ConvolutionND doesn't have dilated parameter

### ISSUE THREAD

**Issue by sharpstill** [chainer/chainer#4712] opened 2018-05-07 04:50 UTC
Why chainer.links.ConvolutionND doesn't have dilated parameter, I am using dilated 1D-conv but cannot find suitable one in chainer.

**Comment by kmaehashi** [comment] 2018-05-07 06:45
We're working on implementing the feature in #4591.

**Comment by kmaehashi** [comment] 2018-05-16 09:42
Closing as duplicate of #2843.

**Closed by kmaehashi** 2018-05-16 09:42 UTC
Labels: st:awaiting-response
