### ISSUE TITLE
Exception in main training loop: module 'cupy.cudnn' has no attribute 'pooling_forward'

### ISSUE THREAD

**Issue by crook52** [chainer/chainer#5685] opened 2018-11-20 06:28 UTC
Hi, 
When I run chainer/examples/imagenet/train_imagenet_data_parallel.py, I got this error.

```
/home/dnn/.pyenv/versions/ymd/bin/python3 /home/dnn/ymd/chainer/examples/imagenet/train_imagenet_data_parallel.py train.txt val.txt
/home/dnn/ymd/chainer/chainer/training/updaters/multiprocess_parallel_updater.py:164: UserWarning: optimizer.lr is changed to 0.00125 by MultiprocessParallelUpdater for new batch size.
format(optimizer.lr))
Exception in main training loop: module 'cupy.cudnn' has no attribute 'pooling_forward'
Traceback (most recent call last):
  File "/home/dnn/ymd/chainer/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/dnn/ymd/chainer/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/dnn/ymd/chainer/chainer/training/updaters/multiprocess_parallel_updater.py", line 237, in update_core
    loss = _calc_loss(self._master, batch)
  File "/home/dnn/ymd/chainer/chainer/training/updaters/multiprocess_parallel_updater.py", line 271, in _calc_loss
    return model(*in_arrays)
  File "/home/dnn/ymd/chainer/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/dnn/ymd/chainer/examples/imagenet/nin.py", line 28, in forward
    h = F.max_pooling_2d(F.relu(self.mlpconv1(x)), 3, stride=2)
  File "/home/dnn/ymd/chainer/chainer/functions/pooling/max_pooling_2d.py", line 383, in max_pooling_2d
    return func.apply((x,))[0]
  File "/home/dnn/ymd/chainer/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home/dnn/ymd/chainer/chainer/function_node.py", line 369, in forward
    return self.forward_gpu(inputs)
  File "/home/dnn/ymd/chainer/chainer/functions/pooling/max_pooling_2d.py", line 64, in forward_gpu
    return super(MaxPooling2D, self).forward_gpu(x)
  File "/home/dnn/ymd/chainer/chainer/functions/pooling/pooling_2d.py", line 54, in forward_gpu
    cudnn.pooling_forward(
Will finalize trainer extensions and updater before reraising the exception.
Process _Worker-3:
```

my environment is
  - Chainer version: 5.0.0
  - CuPy version: 6.0.0a1
  - OS/Platform: Ubuntu18.04
  - CUDA/cuDNN version 10.0/7.4.1

Any help would be useful, thanks.

**Comment by fiarabbit** [comment] 2018-11-20 09:32
[That commit](https://github.com/chainer/chainer/commit/8cb53b0d14557cd682f64cbd40fd540e4e001352#diff-11053239bf4ca0115cf361dc9e1ff917) depends on the "very-latest" (github-master) cupy, which has `cupy.cudnn.pooling_forward`, which is not implemented in cupy==v6.0.0a1.

@crook52 
Try uninstall Chainer and `pip install chainer==v6.0.0a1`, if you want to use cupy==v6.0.0a1

**Comment by fiarabbit** [comment] 2018-11-20 12:10
Also, 
```
>>> import chainer
>>> chainer.print_runtime_info()
```
might help.

**Comment by crook52** [comment] 2018-11-21 08:58
Thank you for your reply.

When I run it with chainer==5.0.0 and cupy==5.0.0, I get this warning.
```
--------------------------------------------------------------------------------
CuPy (cupy) version 5.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy==6.0.0a1'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------
```
So I use cupy==6.0.0a1.
By the way, the same error came when Chainer and Cupy is 5.0.0.

**Comment by crook52** [comment] 2018-11-21 09:10
Thank you for reply.

When I use chainer==5.0.0, I got this warning.

```
--------------------------------------------------------------------------------
CuPy (cupy) version 5.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy==6.0.0a1'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

```
So I use cupy==6.0.0a1.

When chainer and cupy is 5.0.0, I got same error.

And runtime info is below.

```
Platform: Linux-4.15.0-39-generic-x86_64-with-debian-buster-sid
Chainer: 5.0.0
NumPy: 1.15.4
CuPy:
  CuPy Version          : 5.0.0
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10000
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7401
  cuDNN Version         : 7401
  NCCL Build Version    : 2307
iDeep: Not Available

```

**Comment by fiarabbit** [comment] 2018-11-21 09:36
Thanks for giving more information.
I wonder how you installed `chainer`.

I still believe that your chainer installation is collapsed, therefore you should first try to re-install chianer from pip.

**Comment by takagi** [comment] 2018-11-22 05:11
I guess you ran the script in the repository root of, maybe, the master branch, eventually the latest development version of Chainer was used. Would you try it in the example directory?

```
$ cd examples/imagenet
$ python3 train_imagenet_data_parallel.py train.txt val.txt
```

**Comment by crook52** [comment] 2018-11-22 06:06
Thank you both.

I tried 
```
pip uninstall chainer
pip install chainer=='6.0.0a1' --no-cache-dir
```
and 
```
pip uninstall chainer
pip install chainer --no-cache-dir
```

but it isn't resolved.

I always run it in examples/imagenet.

By the way, I'm composing my environment on pyenv.
Is this related??

**Comment by fiarabbit** [comment] 2018-11-22 07:21
@crook52 
> By the way, I'm composing my environment on pyenv.
> Is this related??

It might. I strongly recommend you not to use pyenv.

**Comment by takagi** [comment] 2019-01-10 12:30
Any progress on this issue?

**Comment by takagi** [comment] 2019-02-12 10:34
Please let us close this issue once as it has passed long after the latest update. Feel free to reopen if you would continue to be in trouble.

**Closed by takagi** 2019-02-12 10:34 UTC
Labels: prio:high

**Comment by beam2d** [comment] 2019-02-19 06:29
I hope the problem has been resolved, but just a note: Chainer does not prefer any specific Python environment management tools over the others. If you still have an installation problem with pyenv, do not hesitate to reopen it or open a new issue. Thanks!

**Comment by fiarabbit** [comment] 2019-02-19 07:16
I apologize that I unintentionally led the reader not to use a specific python environment.

For the compensation, I show a small reproduction code of the situation which reported by @crook52 (i.e. the reason of my inference). I just guessed that something like this might have happened for his situation.
```
$ pyenv install 3.6.0 3.6.1
$ pyenv global 3.6.0
$ git clone <chainer-repository>
$ pip install -e <chainer-repository>
$ pyenv local 3.6.1
$ pip install chainer==v5.0.0
$ $PYENV_ROOT/versions/3.6.0/bin/python -c "import chainer;print(chainer.__versions__)"
6.0.0b2
$ python
>>> import chainer
>>> chainer.print_runtime_info()
Platform: Linux-4.4.0-135-generic-x86_64-with-debian-stretch-sid
Chainer: 5.0.0
NumPy: 1.16.1
CuPy: Not Available
iDeep: Not Available
```
