### ISSUE TITLE
The configuration used in forward and backward may be inconsistent

### ISSUE THREAD

**Issue by beam2d** [chainer/chainer#3368] opened 2017-09-11 09:43 UTC
Some functions (e.g. convolution_2d) change their behavior based on `chainer.config`, while they may use different config options between forward and backward. It is currently difficult to change the behavior of backward for selected function applications.

This was easily done when we passed options to each function manually, in which case the same option is used for both forward and backward. I feel we should use the same convention; the configuration used in forward is reused in backward instead of reading the config again in backward from `chainer.config`.

**Comment by beam2d** [comment] 2017-12-10 12:06
The issue looks still existing.

**Comment by kmaehashi** [comment] 2018-04-23 08:51
Duplicate of #2938.

**Closed by kmaehashi** 2018-04-23 08:51 UTC
